export type FieldType =
  | 'text' | 'number' | 'textarea' | 'select' | 'radio'
  | 'chips' | 'radio_conditional' | 'chips_conditional'
  | 'regime_dynamic' | 'risk' | 'risk_tooltip' | 'pdf_upload' | 'drive_upload'

export interface ConditionalField {
  id: string
  label: string
  type: 'text' | 'textarea' | 'pdf_upload'
  ph?: string
}

export interface Field {
  id: string
  label: string
  type: FieldType
  ph?: string
  opts?: string[]
  conditionalOpt?: string
  conditionalField?: ConditionalField
}

export interface Section {
  id: string
  title: string
  desc: string
  fields: Field[]
}

export interface ChecklistDef {
  label: string
  sections: Section[]
}

export const DEFS: Record<string, ChecklistDef> = {
  retail: {
    label: 'Retail / Food Service',
    sections: [
      {
        id: 'pesquisa', title: 'Pesquisa & Identificação',
        desc: 'Dados de identificação e fontes públicas. Clique em "Pesquisar Cliente" para enriquecer automaticamente.',
        fields: [
          { id: 'consultor_nome', label: 'Consultor Responsável', type: 'text', ph: 'Nome do consultor Teknisa' },
          { id: 'consultor_email', label: 'E-mail do Consultor Responsável', type: 'text', ph: 'consultor@teknisa.com' },
          { id: 'sponsor_nome', label: 'Sponsor Executivo — Nome', type: 'text', ph: 'Nome e cargo' },
          { id: 'sponsor_email', label: 'Sponsor Executivo — E-mail', type: 'text', ph: 'sponsor@empresa.com.br' },
          { id: 'sponsor_tel', label: 'Sponsor Executivo — Telefone', type: 'text', ph: '(11) 99999-9999' },
          { id: 'coord_nome', label: 'Coordenador do Projeto no Cliente — Nome', type: 'text', ph: 'Nome e cargo' },
          { id: 'coord_email', label: 'Coordenador do Projeto no Cliente — E-mail', type: 'text', ph: 'coordenador@empresa.com.br' },
          { id: 'coord_tel', label: 'Coordenador do Projeto no Cliente — Telefone', type: 'text', ph: '(11) 99999-9999' },
          { id: 'razao_social', label: 'Razão Social / Nome Fantasia', type: 'text', ph: 'Ex: Grupo Madero Restaurantes S.A.' },
          { id: 'cnpj', label: 'CNPJ Principal', type: 'text', ph: '00.000.000/0001-00' },
          { id: 'site', label: 'Site Oficial', type: 'text', ph: 'https://www.empresa.com.br' },
          { id: 'linkedin', label: 'LinkedIn (empresa)', type: 'text', ph: 'https://linkedin.com/company/...' },
          { id: 'instagram', label: 'Instagram', type: 'text', ph: 'https://instagram.com/...' },
          { id: 'research_extra', label: 'Informações descobertas na pesquisa', type: 'textarea', ph: 'Clique em Pesquisar Cliente para preencher automaticamente...' },
        ],
      },
      {
        id: 'visao', title: 'Perfil do Negócio',
        desc: 'Estrutura, porte e características da operação',
        fields: [
          { id: 'segmento', label: 'Segmento principal', type: 'text', ph: 'Ex: Hamburgueria, Pizzaria, Padaria...' },
          { id: 'tempo_op', label: 'Tempo de Operação', type: 'text', ph: 'Ex: 15 anos' },
          { id: 'qtd_unidades', label: 'Total de Unidades', type: 'number', ph: '0' },
          { id: 'lojas_proprias', label: 'Lojas Próprias', type: 'number', ph: '0' },
          { id: 'franquias', label: 'Franquias', type: 'number', ph: '0' },
          { id: 'regiao', label: 'Região de Atuação', type: 'text', ph: 'Ex: Nacional, Sudeste...' },
          { id: 'expansao', label: 'Expansão prevista (12 meses)', type: 'text', ph: 'Qtd. unidades novas' },
          { id: 'fat_rede', label: 'Faturamento Total da Rede (R$/ano)', type: 'text', ph: 'Ex: R$ 50 milhões' },
          { id: 'fat_loja', label: 'Faturamento médio por loja (R$/mês)', type: 'text', ph: 'Ex: R$ 150 mil' },
          { id: 'ticket_medio', label: 'Ticket Médio (R$)', type: 'number', ph: '0' },
          { id: 'dia_produto_mais_vendido', label: 'Dia da semana e produto mais vendidos', type: 'text', ph: 'Ex: Sábado — X-Burguer' },
          { id: 'horario', label: 'Horário de Funcionamento', type: 'text', ph: 'Ex: 11h–23h / 24h' },
          { id: 'op_24h', label: 'Operação 24h?', type: 'radio', opts: ['Sim', 'Não', 'Algumas unidades'] },
          { id: 'atendimento', label: 'Modelos de Atendimento', type: 'chips', opts: ['Mesa','Balcão','Comanda','Delivery','Autoatendimento (TAA/TAP)','Totem','QR Code','SmartPOS','Garçom com tablet'] },
          { id: 'canais', label: 'Canais de Venda', type: 'chips', opts: ['Consumo local','Retirada','Delivery próprio','Marketplace'] },
          { id: 'objetivo', label: 'Principal objetivo do cliente com o sistema', type: 'textarea', ph: 'O que o cliente quer conquistar?' },
          { id: 'dores', label: 'Maiores dores atuais com sistema / processo atual', type: 'textarea', ph: 'Detalhe as principais dores...' },
          { id: 'nao_perder', label: 'O que o cliente NÃO tem e quer ter? O que tem e não quer perder?', type: 'textarea', ph: 'Descreva...' },
        ],
      },
      {
        id: 'fiscal', title: 'Estrutura Jurídica & Fiscal',
        desc: 'CNPJs, regimes tributários e obrigações fiscais',
        fields: [
          { id: 'qtd_cnpjs', label: 'Nº CNPJs / Empresas (filiais e inscrições estaduais)', type: 'number', ph: '0' },
          { id: 'regime', label: 'Regime Tributário de cada CNPJ', type: 'regime_dynamic' },
          { id: 'contabilidade', label: 'Contabilidade', type: 'radio', opts: ['Interna','Externa','Mista'] },
          { id: 'holding', label: 'Existe Holding?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'docs_fiscais', label: 'Documentos Fiscais Emitidos', type: 'chips', opts: ['NFC-e','NF-e modelo 55','MDF-e','CT-e'] },
          { id: 'ops_fiscais', label: 'Operações com NF modelo 55', type: 'chips', opts: ['Venda','Transferência','Industrialização','Produção própria','Marketplace'] },
          { id: 'sped_tecnisa', label: 'Irá emitir SPED pelo Teknisa ou enviará XMLs para contabilidade?', type: 'radio', opts: ['SPED pelo Teknisa','XMLs para contabilidade','A definir'] },
          { id: 'modulo_contabil', label: 'Foi contratado módulo Contábil? Fechamento de balanço?', type: 'radio', opts: ['Sim — interno','Sim — terceirizado','Não contratado'] },
          { id: 'cert_digital', label: 'Modelo do Certificado Digital', type: 'radio', opts: ['A1 (arquivo) — preferencial','A3 (cartão)','Não possui'] },
        ],
      },
      {
        id: 'infra', title: 'Infraestrutura & Tecnologia',
        desc: 'Hospedagem, hardware, redes e equipamentos por unidade',
        fields: [
          { id: 'hospedagem', label: 'Modelo de hospedagem contratado', type: 'radio', opts: ['SaaS','Hosting','Local (On-premise)'] },
          { id: 'estrutura_loja', label: 'Estrutura atual da loja', type: 'chips', opts: ['Caixa dedicado','Servidor local','Celular','SmartPOS','Tablet'] },
          { id: 'estrutura_proposta', label: 'Estrutura proposta da loja', type: 'chips', opts: ['Caixa dedicado','Servidor Local','Celular','SmartPOS','Tablet'] },
          { id: 'qtd_pdvs', label: 'Quantidade de PDVs por unidade', type: 'number', ph: '0' },
          { id: 'modelo_smartpos', label: 'Modelo de SmartPOS (se aplicável)', type: 'text', ph: 'Ex: Sunmi D3 Pro, PAX A920...' },
          { id: 'internet_redundancia', label: 'Possui redundância de internet?', type: 'radio', opts: ['Sim','Não','Em implantação'] },
          { id: 'rede_tipo', label: 'Rede interna', type: 'radio', opts: ['Cabeada','Wi-Fi','Mista'] },
          { id: 'wifi_exclusivo', label: 'Wi-Fi exclusivo para o sistema ou compartilhado com clientes?', type: 'radio', opts: ['Exclusivo para sistema','Compartilhado com clientes','Sem Wi-Fi'] },
          { id: 'ti_especializado', label: 'Cliente possui TI especializado?', type: 'radio', opts: ['Sim — interno','Sim — terceirizado','Não possui'] },
          { id: 'config_minimas', label: 'Foi apresentado o link de configurações mínimas?', type: 'radio', opts: ['Sim','Não','Pendente'] },
          { id: 'impressoras', label: 'Modelo de impressoras (cupom/cozinha)', type: 'chips', opts: ['Cupom fiscal — Ethernet','Cupom fiscal — USB','Cozinha/Bar — Ethernet','Cozinha/Bar — USB'] },
          { id: 'impressora_nao_homologada', label: 'Possui modelo de impressora não homologado?', type: 'radio_conditional', opts: ['Não','Sim'], conditionalOpt: 'Sim', conditionalField: { id: 'impressora_nao_homologada_modelo', label: 'Informe o modelo da impressora não homologada', type: 'text', ph: 'Ex: Epson TM-T20, Bematech MP-4200...' } },
          { id: 'kds_tipo', label: 'Possui KDS (Kitchen Display System)?', type: 'radio', opts: ['Sim','Não','Em avaliação'] },
          { id: 'kds_tipos', label: 'Tipos de KDS (se possui)', type: 'chips', opts: ['Produção','Montagem','Expedição'] },
          { id: 'balanca_pinpad', label: 'Possui balança e/ou pinpad? Quais marcas/modelos?', type: 'text', ph: 'Ex: Balança Toledo + PinPad Ingenico IPP350' },
          { id: 'catraca', label: 'Possui catraca? Qual modelo?', type: 'text', ph: 'Modelo ou Não possui' },
          { id: 'leitor_rfid', label: 'Existem leitores de código de barras e/ou RFID/Crachá?', type: 'radio', opts: ['Sim — código de barras','Sim — RFID/Crachá','Ambos','Não'] },
        ],
      },
      {
        id: 'pdv', title: 'Operação de Vendas (PDV)',
        desc: 'Configurações fiscais, pagamentos, TEF e regras de venda',
        fields: [
          { id: 'modelo_fiscal', label: 'Modelo de transmissão de cupom fiscal', type: 'radio', opts: ['NFC-e','NFE'] },
          { id: 'token_csc', label: 'Cliente já possui Token CSC (para NFC-e)?', type: 'radio', opts: ['Sim','Não','A providenciar'] },
          { id: 'tef', label: 'Utiliza TEF?', type: 'radio', opts: ['Sim','Não','Em avaliação'] },
          { id: 'tef_fiserv', label: 'Cliente ciente da necessidade de contratar Fiserv para TEF?', type: 'radio', opts: ['Sim, ciente','Não se aplica'] },
          { id: 'nocash', label: 'Tem NoCash?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'nocash_fiserv', label: 'NoCash: cliente ciente de contratar FISERV Carat?', type: 'radio', opts: ['Sim, ciente','Não se aplica'] },
          { id: 'nocash_stores', label: 'NoCash: cliente quer Android e iOS?', type: 'radio', opts: ['Sim, ciente das contas dev','Apenas Android','Apenas iOS','Não se aplica'] },
          { id: 'eattake', label: 'Possui EatTake? Cliente ciente das taxas Stone?', type: 'radio', opts: ['Sim, ciente','Não possui'] },
          { id: 'adquirencia', label: 'Adquirência utilizada', type: 'chips', opts: ['Rede','Cielo','Stone','GetNet','Safra','PagSeguro','Outro'] },
          { id: 'odhen_pos', label: 'Irão utilizar OdhenPOS? Qual adquirente?', type: 'text', ph: 'Ex: Sim — Stone / Não utiliza' },
          { id: 'formas_pagamento', label: 'Formas de Pagamento nos PDVs', type: 'chips', opts: ['Dinheiro','Crédito','Débito','PIX','Vale Refeição','Vale Alimentação','Crédito próprio','Cortesia'] },
          { id: 'conciliador_cartoes', label: 'Terá conciliador de cartões?', type: 'radio_conditional', opts: ['Sim, já contratado','Sim, ainda não contratado','Não terá'], conditionalOpt: 'Sim, já contratado|Sim, ainda não contratado', conditionalField: { id: 'conciliador_van', label: 'Qual a VAN (conciliadora contratada)?', type: 'text', ph: 'Ex: Braspag, Cielo Conciliador, Swap...' } },
          { id: 'venda_nao_fiscal', label: 'Cliente terá venda não fiscal? Qual modalidade?', type: 'text', ph: 'Ex: Cortesia, funcionários... ou Não' },
          { id: 'politica_desconto', label: 'Possui política de desconto? Qual mecânica?', type: 'textarea', ph: 'Descreva as regras de desconto...' },
          { id: 'precos_diferenciados', label: 'Trabalham com preços diferenciados?', type: 'text', ph: 'Ex: Diferente por canal, delivery vs salão...' },
          { id: 'etiqueta', label: 'Precisa de etiqueta (gôndola) para venda?', type: 'radio', opts: ['Sim','Não','Outro tipo de etiqueta'] },
          { id: 'venda_peso', label: 'Haverá venda por peso (self-service)?', type: 'radio', opts: ['Sim — com controle de estoque debatido','Sim — controle não debatido','Não'] },
          { id: 'encomendas', label: 'Cliente possui encomendas? Qual solução?', type: 'text', ph: 'Descreva ou Não possui' },
          { id: 'garcom_comissao', label: 'Existem garçons? Política de comissão?', type: 'text', ph: 'Ex: Sim, 10% automático / Não possui garçons' },
          { id: 'painel_senha', label: 'Terá painel de senha / Pager digital?', type: 'radio', opts: ['Painel','Pager','Ambos','Não se aplica'] },
          { id: 'taa_tap', label: 'Haverá TAA (autoatendimento) ou TAP (autopagamento)?', type: 'text', ph: 'Ex: Sim, TAA — Android 12 / Não' },
        ],
      },
      {
        id: 'delivery', title: 'Delivery & Integrações',
        desc: 'Plataformas, motoboy, integrações e APIs',
        fields: [
          { id: 'delivery_plat', label: 'Plataformas de Delivery contratadas', type: 'chips', opts: ['iFood','Rappi','Uber Eats','99food','Keeta','Delivery próprio'] },
          { id: 'hub', label: 'Usa Hub Integrador?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'pct_delivery', label: '% do faturamento em Delivery', type: 'text', ph: 'Ex: 35%' },
          { id: 'motoboy', label: 'Possui motoboy próprio e rastreio de rotas?', type: 'radio', opts: ['Sim — com rastreio','Sim — sem rastreio','Não, terceirizado','Não realiza delivery'] },
          { id: 'integracoes', label: 'Integrações contratadas ou necessárias', type: 'chips', opts: ['Delivery','Contabilidade','CRM','Fidelidade','E-commerce','APIs externas','Pedido online'] },
          { id: 'api_nao_delivery', label: 'Existe alguma API contratada que não seja de delivery?', type: 'textarea', ph: 'Descreva as APIs ou Não possui' },
          { id: 'api_vendas_teknisa', label: 'Cliente precisará da API de Vendas Teknisa? Ciente do custo adicional?', type: 'radio', opts: ['Sim, ciente do custo','Não precisará'] },
          { id: 'crm_atual', label: 'CRM / Programa de Fidelidade atual', type: 'text', ph: 'Nome do sistema ou Não possui' },
          { id: 'crm_status', label: 'Status do CRM/Fidelidade', type: 'radio', opts: ['Sim ativo','Sim subutilizado','Não possui'] },
        ],
      },
      {
        id: 'produtos', title: 'Produtos, Produção & Estoque',
        desc: 'Cardápio, fichas técnicas, compras e controles de estoque',
        fields: [
          { id: 'qtd_skus', label: 'Quantidade total de SKUs (produtos)', type: 'number', ph: '0' },
          { id: 'tipos_produto', label: 'Tipos de Produtos', type: 'chips', opts: ['Revenda','Produção própria','Semi-acabado','Molhos / Bases','Insumos'] },
          { id: 'producao', label: 'Tipo de Produção', type: 'radio', opts: ['Só revenda','Produção própria','Ambos'] },
          { id: 'producao_estocada', label: 'Produz algo estocado, ou tudo feito na hora?', type: 'radio', opts: ['Produz e estoca','Tudo feito na hora','Misto'] },
          { id: 'estoque_negativo', label: 'Cliente ciente que não trabalhamos com estoque negativo?', type: 'radio', opts: ['Sim, ciente'] },
          { id: 'estoque_centralizado', label: 'Possui estoque centralizado?', type: 'radio', opts: ['Sim','Não','Parcialmente'] },
          { id: 'ficha_tec', label: 'Ficha Técnica dos produtos', type: 'radio', opts: ['Sim — atualizada','Sim — desatualizada','Não possui'] },
          { id: 'cardapio_pdf', label: 'Cliente possui cardápio em PDF para disponibilizar?', type: 'radio_conditional', opts: ['Não','Sim'], conditionalOpt: 'Sim', conditionalField: { id: 'cardapio_pdf_upload', label: 'Upload do cardápio em PDF', type: 'pdf_upload', ph: 'Selecionar arquivo PDF...' } },
          { id: 'combos', label: 'Quais combos o cliente possui?', type: 'textarea', ph: 'Descreva os tipos de combo ou Não possui' },
          { id: 'inv_freq', label: 'Frequência de contagem física do estoque', type: 'select', opts: ['Selecione','Diário','Semanal','Quinzenal','Mensal','Eventual'] },
          { id: 'almoxarifado', label: 'Trabalham com almoxarifado? Quantos e quais?', type: 'text', ph: 'Ex: 2 almoxarifados — central e cozinha / Não' },
          { id: 'unidade_medida_diff', label: 'Produtos comprados em unidade diferente da consumida?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'estoque_cnpj_diff', label: 'Estoques físicos iguais com CNPJs fiscalmente separados?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'estoque_ctrl', label: 'Controles de Estoque utilizados', type: 'chips', opts: ['Curva ABC','Lote/validade','Transferência entre lojas','WMS','FEFO/FIFO'] },
          { id: 'divergencia', label: 'Divergência recorrente de estoque?', type: 'radio', opts: ['Sim','Não','Às vezes'] },
          { id: 'compra_central', label: 'Modelo de Compras', type: 'radio', opts: ['Centralizada','Por unidade','Mista'] },
          { id: 'alcada_compras', label: 'Existe limite de valor para compradores? Quem aprova o Pedido de Compra?', type: 'textarea', ph: 'Descreva as alçadas ou Não possui' },
          { id: 'sem_cotacao', label: 'Cliente ciente que o módulo Compras não tem cotação nativa?', type: 'radio', opts: ['Sim, ciente'] },
          { id: 'portal_compras', label: 'Foi apresentado o Portal de Compras?', type: 'radio', opts: ['Sim, apresentado','Não possui/não aplicável','Pendente apresentação'] },
        ],
      },
      {
        id: 'financeiro', title: 'Financeiro & ERP',
        desc: 'Fluxo financeiro, bancos, CNAB e apuração de resultados',
        fields: [
          { id: 'aprovacao_pagamentos', label: 'Pagamentos necessitam de aprovação? Como são definidas as alçadas?', type: 'textarea', ph: 'Descreva o fluxo ou Não possui' },
          { id: 'conciliacao_bancaria', label: 'Conciliação bancária', type: 'radio', opts: ['Manual','Via importação OFX','Automática via API','A definir'] },
          { id: 'cnab_liberacao', label: 'Cliente ciente que precisa liberar o CNAB com o banco?', type: 'radio', opts: ['Sim, ciente','Não informado','Não se aplica'] },
          { id: 'cnab_receber', label: 'Utilizam CNAB/DDA para boletos (Contas a Receber)?', type: 'radio', opts: ['Sim','Não','A definir'] },
          { id: 'cnab_pagar', label: 'Utilizam CNAB/DDA para boletos (Contas a Pagar)?', type: 'radio', opts: ['Sim','Não','A definir'] },
          { id: 'bancos', label: 'Bancos utilizados', type: 'text', ph: 'Ex: Itaú, Bradesco, Banco do Brasil...' },
          { id: 'apuracao_resultado', label: 'Como a empresa apura resultados?', type: 'chips', opts: ['Por filial','Por departamento','Por projeto','Por unidade de negócio','Consolidado'] },
          { id: 'plano_contas', label: 'Já existe Plano de Contas padrão a ser importado?', type: 'radio', opts: ['Sim, já disponível','Não, será criado','A definir'] },
          { id: 'dre_apresentado', label: 'Foi apresentado o DRE ao cliente?', type: 'radio', opts: ['Sim','Não','Pendente'] },
        ],
      },
      {
        id: 'producao_industrial', title: 'Produção Industrial (se aplicável)',
        desc: 'Para clientes com fábrica, cozinha central ou produção estruturada',
        fields: [
          { id: 'prod_modelo', label: 'Produção é por pedidos das unidades (SC) ou por planejamento (MRP)?', type: 'radio', opts: ['Por pedidos de unidades (SC)','Por planejamento (MRP)','Misto','Não se aplica'] },
          { id: 'prod_integracao_fabrica', label: 'Realiza integração entre lojas e fábricas? Como chegam as solicitações?', type: 'textarea', ph: 'Descreva o fluxo de abastecimento ou Não se aplica' },
          { id: 'prod_base_calculo', label: 'Base de cálculo do plano de produção', type: 'chips', opts: ['Histórico de vendas','Sazonalidade','Estoque mín/máx','Meta de venda','A definir'] },
          { id: 'prod_mao_obra', label: 'Existe apontamento de mão de obra no chão de fábrica?', type: 'radio', opts: ['Sim','Não','Não se aplica'] },
          { id: 'prod_importacao_ft', label: 'Cliente ciente que não tem importação de ficha técnica?', type: 'radio', opts: ['Sim, ciente','Não se aplica'] },
          { id: 'prod_maquinas', label: 'Existe controle de tempo de uso de máquinas/equipamentos?', type: 'radio', opts: ['Sim','Não','Não se aplica'] },
          { id: 'prod_desperdicio', label: 'Como é controlado o desperdício e variação de rendimento dos lotes?', type: 'textarea', ph: 'Descreva o processo ou Não controla' },
          { id: 'prod_lote_tipo', label: 'Controle de lote', type: 'radio', opts: ['Sequencial','Por data de fabricação','Lote do fornecedor','Não possui','Não se aplica'] },
          { id: 'prod_validade', label: 'Como é o controle de validade dos produtos?', type: 'textarea', ph: 'Descreva o processo' },
          { id: 'prod_logistica', label: 'Logística: frota própria ou terceirizada? Necessidade de roteirização e MDF-e?', type: 'text', ph: 'Ex: Frota própria, necessita roteirização e MDF-e / Terceirizada' },
        ],
      },
      {
        id: 'sistemas', title: 'Sistemas, Tecnologia & Gestão',
        desc: 'Stack atual, integrações, KPIs e maturidade de gestão',
        fields: [
          { id: 'erp_atual', label: 'ERP/Sistema Atual', type: 'text', ph: 'Ex: TOTVS, Linx, nenhum...' },
          { id: 'pdv_atual', label: 'Sistema de PDV', type: 'text', ph: 'Nome do sistema' },
          { id: 'bi_atual', label: 'BI / Relatórios', type: 'text', ph: 'Nome ou Nenhum' },
          { id: 'rh_atual', label: 'RH / Folha', type: 'text', ph: 'Nome ou Nenhum' },
          { id: 'funciona', label: 'O que funciona bem no sistema atual? (não pode perder)', type: 'textarea', ph: 'Descreva...' },
          { id: 'planilhas', label: 'Existem planilhas paralelas ao sistema?', type: 'radio', opts: ['Sim, muitas','Algumas','Não'] },
          { id: 'relatorios_atuais', label: '3 a 5 relatórios que o cliente usa hoje', type: 'textarea', ph: 'Ex: 1. Vendas por produto, 2. CMV mensal...' },
          { id: 'reuniao_gestao', label: 'Qual dia do mês o cliente reunirá para analisar relatórios?', type: 'text', ph: 'Ex: Todo dia 5 / Não tem rotina definida' },
          { id: 'kpis', label: 'KPIs Acompanhados', type: 'chips', opts: ['CMV','Margem','Ticket Médio','Venda/hora','Performance Delivery','Ruptura','Desperdício','EBITDA','NPS','Produtividade'] },
          { id: 'controle_cmv', label: 'Cliente controla CMV dos produtos? Qual cálculo realiza?', type: 'text', ph: 'Ex: Sim — custo médio ponderado / Não controla' },
          { id: 'maturidade', label: 'Nível de Maturidade de Gestão', type: 'radio', opts: ['Alta','Média','Baixa'] },
          { id: 'proc_doc', label: 'Processos documentados? Responsáveis por área?', type: 'radio', opts: ['Sim — processos e responsáveis definidos','Parcialmente','Não possui processos definidos'] },
          { id: 'cult_kpi', label: 'Cultura de indicadores?', type: 'radio', opts: ['Sim','Em desenvolvimento','Não'] },
          { id: 'nps', label: 'Pesquisa de satisfação / NPS?', type: 'radio', opts: ['Sim','Não','Em avaliação'] },
          { id: 'base_clientes', label: 'Base ativa de clientes', type: 'text', ph: 'Ex: 500 mil cadastros' },
        ],
      },
      {
        id: 'projeto', title: 'Escopo, Projeto & Pessoas-Chave',
        desc: 'Comprometimentos, cronograma, equipe e expectativas alinhadas',
        fields: [
          { id: 'resultado', label: 'Resultado esperado com o projeto', type: 'textarea', ph: 'KPIs ou melhorias esperadas...' },
          { id: 'compromissos_fora_contrato', label: 'Compromissos assumidos na venda FORA do produto padrão', type: 'textarea', ph: 'Liste o que foi prometido além do escopo padrão...' },
          { id: 'nao_incluso', label: 'O que NÃO está incluso no contrato?', type: 'textarea', ph: 'Liste exclusões e limitações explícitas...' },
          { id: 'personalizacoes', label: 'Necessidades de personalização de sistema', type: 'textarea', ph: 'Nº dos chamados ou descrição das solicitações...' },
          { id: 'go_live', label: 'Data acordada da virada da primeira loja', type: 'text', ph: 'Ex: 15/08/2025' },
          { id: 'data_critica', label: 'Data crítica ou prazo máximo', type: 'text', ph: 'Ex: Fechamento fiscal dezembro / Black Friday' },
          { id: 'expectativa_prazo', label: 'Expectativa de prazo para entrada em produção e conclusão do projeto', type: 'text', ph: 'Ex: Go-live em 3 meses, projeto completo em 6 meses' },
          { id: 'custos_visitas', label: 'Foi mencionado sobre custos de agendas/visitas presenciais?', type: 'radio', opts: ['Sim, cliente ciente','Não foi mencionado','Não se aplica'] },
          { id: 'sponsor', label: 'Sponsor Executivo', type: 'text', ph: 'Nome e cargo' },
          { id: 'pessoas_chave', label: 'Pessoas-chave do cliente para o projeto', type: 'textarea', ph: 'Ex: João Silva — Gerente de TI, Maria Costa — Nutricionista...' },
          { id: 'freq_status_report', label: 'Frequência de reunião de status report com o sponsor', type: 'radio', opts: ['Semanal','Quinzenal','Mensal','A definir'] },
          { id: 'modulos_prio', label: 'Módulos Contratados / Prioritários', type: 'chips', opts: ['PDV','Estoque','Financeiro','Fiscal','Delivery','BI','CRM/Fidelidade','RH','Produção','Compras','NoCash','EatTake','TAA/TAP','KDS','Portal de Compras','IA/Analytics'] },
        ],
      },
      {
        id: 'riscos', title: 'Alertas Comerciais & Riscos para Implantação',
        desc: '⚠ Seção obrigatória — sinalize todos os pontos críticos ao time de implantação',
        fields: [
          { id: 'alertas', label: 'Alertas Identificados', type: 'chips', opts: ['Operação complexa','Sem processos definidos','Infraestrutura ruim','Alta expectativa vs. realidade','Dependência de terceiros','Equipe resistente','Histórico ruim com sistemas','Falta responsável interno','Baixa maturidade gerencial','Custo de visitas presenciais não comunicado'] },
          { id: 'op_complexa_desc', label: 'Operação complexa? Descreva', type: 'textarea', ph: 'Descreva a complexidade ou Não se aplica' },
          { id: 'promessas_fora_escopo', label: 'Alta expectativa vs. realidade — o que foi prometido além do escopo?', type: 'textarea', ph: 'Descreva ou Não se aplica' },
          { id: 'dependencia_terceiros', label: 'Dependência de terceiros? Quais?', type: 'textarea', ph: 'Liste as dependências ou Não se aplica' },
          { id: 'rotina_nao_atendida', label: 'Existe alguma rotina que o sistema NÃO atende? Nº do chamado', type: 'textarea', ph: 'Ex: #12345 — Relatório X / Não identificado' },
          { id: 'gargalos', label: 'O que pode ser gargalo na operação ou na implantação?', type: 'textarea', ph: 'Antecipe os obstáculos previstos...' },
          { id: 'risco', label: 'Classificação de Risco Global', type: 'risk_tooltip' },
          { id: 'concorrencia', label: 'Concorrência em avaliação', type: 'chips', opts: ['TOTVS','Linx','Sankhya','Aloha','Outro'] },
          { id: 'obs', label: 'Observações gerais do comercial para a equipe de implantação', type: 'textarea', ph: 'Tudo que a implantação precisa saber...' },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════
  // ERP INDUSTRIAL — 17 seções — espelho fiel do documento
  // ══════════════════════════════════════════════════════════
  erp: {
    label: 'ERP Industrial',
    sections: [
      // ── 01 PESQUISA ────────────────────────────────────────
      {
        id: 'pesquisa', title: 'Pesquisa & Identificação',
        desc: 'Dados de identificação e fontes públicas. Clique em "Pesquisar Cliente" para enriquecer automaticamente.',
        fields: [
          { id: 'consultor_nome', label: 'Consultor Responsável', type: 'text', ph: 'Nome do consultor Teknisa' },
          { id: 'consultor_email', label: 'E-mail do Consultor Responsável', type: 'text', ph: 'consultor@teknisa.com' },
          { id: 'sponsor_nome', label: 'Sponsor Executivo — Nome', type: 'text', ph: 'Nome e cargo' },
          { id: 'sponsor_email', label: 'Sponsor Executivo — E-mail', type: 'text', ph: 'sponsor@empresa.com.br' },
          { id: 'sponsor_tel', label: 'Sponsor Executivo — Telefone', type: 'text', ph: '(11) 99999-9999' },
          { id: 'coord_nome', label: 'Coordenador do Projeto no Cliente — Nome', type: 'text', ph: 'Nome e cargo' },
          { id: 'coord_email', label: 'Coordenador do Projeto no Cliente — E-mail', type: 'text', ph: 'coordenador@empresa.com.br' },
          { id: 'coord_tel', label: 'Coordenador do Projeto no Cliente — Telefone', type: 'text', ph: '(11) 99999-9999' },
          { id: 'razao_social', label: 'Razão Social / Nome Fantasia', type: 'text', ph: 'Nome da empresa' },
          { id: 'cnpj', label: 'CNPJ Principal', type: 'text', ph: '00.000.000/0001-00' },
          { id: 'site', label: 'Site Oficial', type: 'text', ph: 'https://www.empresa.com.br' },
          { id: 'linkedin', label: 'LinkedIn (empresa)', type: 'text', ph: 'https://linkedin.com/company/...' },
          { id: 'instagram', label: 'Instagram', type: 'text', ph: 'https://instagram.com/...' },
          { id: 'research_extra', label: 'Informações descobertas na pesquisa', type: 'textarea', ph: 'Preencha automaticamente ou adicione manualmente...' },
        ],
      },
        desc: 'Estrutura da empresa, segmento e presença operacional',
        fields: [
          { id: 'segmento', label: 'Segmento Principal', type: 'chips', opts: ['Indústria','Distribuição','Atacado','Facilities','Serviços','Logística','Importação','Produção sob encomenda'] },
          { id: 'subsegmento', label: 'Subsegmento', type: 'chips', opts: ['Alimentício','Metalúrgico','Químico','Têxtil','Higiene/Limpeza','Construção','Hospitalar','Tecnologia','Outros'] },
          { id: 'tempo_op', label: 'Tempo de Atuação', type: 'text', ph: 'Ex: 20 anos' },
          { id: 'regiao', label: 'Região de Atuação', type: 'text', ph: 'Ex: Nacional, Sudeste...' },
          { id: 'qtd_unidades', label: 'Número total de unidades', type: 'number', ph: '0' },
          { id: 'matriz', label: 'Qual será a organização principal (matriz)?', type: 'text', ph: 'Ex: Sede São Paulo' },
          { id: 'filiais', label: 'Filiais', type: 'number', ph: '0' },
          { id: 'cds', label: 'Centros de Distribuição', type: 'number', ph: '0' },
          { id: 'fabricas', label: 'Fábricas', type: 'number', ph: '0' },
          { id: 'estoques', label: 'Estoques (depósitos)', type: 'number', ph: '0' },
          { id: 'escritorios', label: 'Escritórios', type: 'number', ph: '0' },
          { id: 'ops_terceirizadas', label: 'Operações terceirizadas', type: 'number', ph: '0' },
          { id: 'obras_postos', label: 'Obras / Postos / Clientes (Facilities)', type: 'number', ph: '0' },
          { id: 'fat_total', label: 'Faturamento Total (R$/ano)', type: 'text', ph: 'Ex: R$ 200 milhões' },
        ],
      },
      // ── 03 ESTRUTURA SOCIETÁRIA E FISCAL ───────────────────
      {
        id: 'fiscal', title: 'Estrutura Societária & Fiscal',
        desc: 'CNPJs, regimes tributários, obrigações fiscais e contábeis',
        fields: [
          { id: 'qtd_cnpjs', label: 'Quantidade de empresas e quais (CNPJs)', type: 'number', ph: '0' },
          { id: 'regime', label: 'Regime tributário de cada empresa', type: 'regime_dynamic' },
          { id: 'insc_estaduais', label: 'Quantidade de inscrições estaduais', type: 'number', ph: '0' },
          { id: 'qtd_filiais_fiscal', label: 'Quantidade de filiais (fiscal)', type: 'number', ph: '0' },
          { id: 'holding', label: 'Existe Holding?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'importacao', label: 'Existe operação internacional / importação?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'contabilidade', label: 'Contabilidade', type: 'radio', opts: ['Interna','Externa','Mista'] },
          { id: 'responsavel_fiscal', label: 'Responsável fiscal (nome e cargo)', type: 'text', ph: 'Ex: João Silva — Coordenador Fiscal' },
          { id: 'controladoria', label: 'Possui Controladoria?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'auditoria_externa', label: 'Possui Auditoria Externa?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'docs_fiscais', label: 'Documentos Fiscais Emitidos', type: 'chips', opts: ['NF-e modelo 55','NFS-e','CT-e','MDF-e','NFC-e','Conhecimento de transporte'] },
          { id: 'tipos_op', label: 'Tipos de Operação Fiscal', type: 'chips', opts: ['Venda','Transferência','Industrialização','Remessa','Importação','Exportação','Consignação','Bonificação','Comodato'] },
          { id: 'particularidades_trib', label: 'Possui particularidades tributárias?', type: 'textarea', ph: 'Descreva ou Não possui' },
          { id: 'beneficios_fiscais', label: 'Possui benefícios fiscais?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'subst_trib', label: 'Possui Substituição Tributária?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'multi_estados', label: 'Opera em múltiplos estados?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'cert_digital', label: 'Modelo do Certificado Digital', type: 'radio', opts: ['A1 (arquivo) — preferencial','A3 (cartão)','Não possui'] },
        ],
      },
      // ── 04 ESTRUTURA OPERACIONAL ───────────────────────────
      {
        id: 'operacao', title: 'Estrutura Operacional',
        desc: 'Modelo operacional, volumes e gestão da operação',
        fields: [
          { id: 'modelo_op', label: 'Modelo Operacional', type: 'chips', opts: ['Produção própria','Distribuição','Prestação de serviços','Operação híbrida'] },
          { id: 'tipo_prod', label: 'Tipo de Produção', type: 'chips', opts: ['Contínua','Sob demanda','Discreta','Processo contínuo'] },
          { id: 'pedidos_mes', label: 'Quantidade média de pedidos/mês', type: 'number', ph: '0' },
          { id: 'notas_mes', label: 'Quantidade média de notas emitidas/mês', type: 'number', ph: '0' },
          { id: 'fat_mensal', label: 'Faturamento mensal médio (R$)', type: 'text', ph: 'Ex: R$ 10 milhões' },
          { id: 'usuarios', label: 'Quantidade de usuários previstos', type: 'number', ph: '0' },
          { id: 'op_24h', label: 'Operação 24h?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'turnos', label: 'Possui turnos?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'gestao_tipo', label: 'Gestão centralizada ou descentralizada?', type: 'radio', opts: ['Centralizada','Descentralizada','Mista'] },
          { id: 'planej_op', label: 'Existe planejamento operacional?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'pcp', label: 'Existe PCP?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'mrp', label: 'Existe MRP?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'ctrl_capacidade', label: 'Existe controle de capacidade produtiva?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'gestao_contratos', label: 'Existe gestão de contratos?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'gestao_cc', label: 'Existe gestão por centro de custo?', type: 'radio', opts: ['Sim','Não'] },
        ],
      },
      // ── 05 PRODUTOS, PRODUÇÃO E ENGENHARIA ─────────────────
      {
        id: 'producao', title: 'Produtos, Produção & Engenharia',
        desc: 'Estrutura de produtos, BOM, produção e engenharia',
        fields: [
          { id: 'qtd_skus', label: 'Quantidade aproximada de SKUs', type: 'number', ph: '0' },
          { id: 'tipos_prod', label: 'Trabalha com', type: 'chips', opts: ['Matéria-prima','Produto acabado','Semiacabado','Revenda','Serviços'] },
          { id: 'rastreab', label: 'Existe rastreabilidade?', type: 'radio', opts: ['Sim','Não','Em implantação'] },
          { id: 'ctrl_lote', label: 'Controle de lote/validade?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'serializacao', label: 'Serialização?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'producao_interna', label: 'Produz internamente?', type: 'radio', opts: ['Sim','Parcialmente','Não'] },
          { id: 'prod_terceirizada', label: 'Produção terceirizada?', type: 'radio', opts: ['Sim','Não','Parcialmente'] },
          { id: 'apontamento_prod', label: 'Necessita apontamento de produção?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'chao_fabrica', label: 'Necessita chão de fábrica?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'ordem_prod', label: 'Utiliza Ordem de Produção?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'eng_produto', label: 'Utiliza engenharia de produto?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'ctrl_perdas', label: 'Controle de perdas/refugo?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'ctrl_manutencao', label: 'Controle de manutenção?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'bom', label: 'Possui estrutura/BOM?', type: 'radio', opts: ['Sim','Parcialmente','Não'] },
          { id: 'ctrl_revisao', label: 'Controle de revisão?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'ctrl_versoes', label: 'Controle de versões?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'ficha_tec', label: 'Possui ficha técnica?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'cad_plm', label: 'Integra CAD/PLM?', type: 'radio', opts: ['Sim','Não','Em avaliação'] },
        ],
      },
      // ── 06 ESTOQUE, LOGÍSTICA E COMPRAS ────────────────────
      {
        id: 'logistica', title: 'Estoque, Logística & Compras',
        desc: 'Armazéns, inventário, distribuição e gestão de suprimentos',
        fields: [
          { id: 'armazens', label: 'Quantidade de armazéns/depósitos', type: 'number', ph: '0' },
          { id: 'inv_rotativo', label: 'Inventário rotativo ou geral?', type: 'radio', opts: ['Rotativo','Geral','Ambos'] },
          { id: 'freq_inventario', label: 'Frequência de inventário', type: 'select', opts: ['Selecione','Diário','Semanal','Quinzenal','Mensal','Trimestral','Anual'] },
          { id: 'ctrl_endereco', label: 'Controle por endereço?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'fefo_fifo', label: 'Controle FEFO/FIFO?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'ctrl_validade', label: 'Controle de validade?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'ctrl_lote_est', label: 'Controle de lote (estoque)?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'wms', label: 'Possui WMS?', type: 'radio', opts: ['Sim','Não','Em implantação'] },
          { id: 'frota', label: 'Frota própria?', type: 'radio', opts: ['Sim','Não','Mista'] },
          { id: 'transportadoras', label: 'Transportadoras terceirizadas?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'roteirizacao', label: 'Possui roteirização?', type: 'radio', opts: ['Sim','Não','Em avaliação'] },
          { id: 'ctrl_frete', label: 'Controle de frete?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'tabela_frete', label: 'Tabela de frete?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'cross_docking', label: 'Cross docking?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'log_reversa', label: 'Logística reversa?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'compras_tipo', label: 'Compras centralizadas?', type: 'radio', opts: ['Centralizadas','Descentralizadas','Mistas'] },
          { id: 'workflow_compras', label: 'Workflow de aprovação (compras)?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'cotacao', label: 'Processo de cotação?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'fornec_homologados', label: 'Fornecedores homologados?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'contratos_fornec', label: 'Contratos de fornecimento?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'lead_time', label: 'Lead time médio de compras', type: 'text', ph: 'Ex: 15 dias' },
        ],
      },
      // ── 07 COMERCIAL E FATURAMENTO ─────────────────────────
      {
        id: 'comercial', title: 'Comercial & Faturamento',
        desc: 'Força de vendas, CRM e modelo de faturamento',
        fields: [
          { id: 'qtd_vendedores', label: 'Quantidade de vendedores', type: 'number', ph: '0' },
          { id: 'representantes', label: 'Possui representantes comerciais?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'comissao', label: 'Trabalha com comissão?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'crm_atual', label: 'Utiliza CRM?', type: 'radio_conditional', opts: ['Sim','Não'], conditionalOpt: 'Sim', conditionalField: { id: 'crm_nome', label: 'Qual CRM utiliza?', type: 'text', ph: 'Ex: Salesforce, RD Station, HubSpot...' } },
          { id: 'metas_comerciais', label: 'Possui metas comerciais?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'pipeline', label: 'Gestão de pipeline?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'ticket_medio', label: 'Ticket médio (R$)', type: 'text', ph: 'Ex: R$ 50 mil' },
          { id: 'vol_pedidos', label: 'Volume médio de pedidos/mês', type: 'number', ph: '0' },
          { id: 'periodicidade_fat', label: 'Periodicidade de faturamento', type: 'radio', opts: ['Diário','Semanal','Quinzenal','Mensal','Por projeto'] },
          { id: 'fat_contrato', label: 'Faturamento por contrato/projeto?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'fat_recorrente', label: 'Faturamento recorrente?', type: 'radio', opts: ['Sim','Não','Parcialmente'] },
        ],
      },
      // ── 08 FINANCEIRO E CONTROLADORIA ──────────────────────
      {
        id: 'financeiro', title: 'Financeiro & Controladoria',
        desc: 'Controle financeiro, bancos, custos e estrutura contábil',
        fields: [
          { id: 'ctrl_financeiro_central', label: 'Controle financeiro centralizado?', type: 'radio', opts: ['Sim','Não','Parcialmente'] },
          { id: 'fluxo_caixa', label: 'Fluxo de caixa?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'orcamento', label: 'Orçamento?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'forecast', label: 'Forecast?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'ctrl_cc', label: 'Controle por centro de custo?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'ctrl_projeto', label: 'Controle por projeto?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'dre_gerencial', label: 'DRE gerencial?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'bancos', label: 'Quais bancos utiliza?', type: 'text', ph: 'Ex: Itaú, Bradesco, Banco do Brasil...' },
          { id: 'cnab', label: 'Utiliza CNAB?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'conciliacao_bancaria', label: 'Possui conciliação bancária?', type: 'radio', opts: ['Sim — manual','Sim — automatizada','Não'] },
          { id: 'pix_integrado', label: 'PIX integrado?', type: 'radio', opts: ['Sim','Não','Em avaliação'] },
          { id: 'cobranca_registrada', label: 'Cobrança registrada?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'antecipacao', label: 'Antecipação de recebíveis?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'custo_padrao', label: 'Possui custo padrão?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'custo_medio', label: 'Custo médio?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'rateios', label: 'Rateios?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'ctrl_margem', label: 'Controle de margem?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'formacao_preco', label: 'Formação de preço?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'aprovacao_pagamentos', label: 'Pagamentos necessitam de aprovação? Quais alçadas?', type: 'textarea', ph: 'Descreva o fluxo ou Não possui' },
          { id: 'plano_contas', label: 'Já existe Plano de Contas padrão a ser importado?', type: 'radio', opts: ['Sim, já disponível','Não, será criado','A definir'] },
        ],
      },
      // ── 09 FACILITIES (quando aplicável) ───────────────────
      {
        id: 'facilities', title: 'Facilities (quando aplicável)',
        desc: 'Gestão de contratos, postos, equipes e SLA — preencha se o cliente opera em facilities',
        fields: [
          { id: 'qtd_contratos', label: 'Quantidade de contratos/postos', type: 'number', ph: '0' },
          { id: 'gestao_sla', label: 'Gestão de SLA?', type: 'radio', opts: ['Sim','Não','Não se aplica'] },
          { id: 'ctrl_equipes', label: 'Controle de equipes?', type: 'radio', opts: ['Sim','Não','Não se aplica'] },
          { id: 'ctrl_escalas', label: 'Controle de escalas?', type: 'radio', opts: ['Sim','Não','Não se aplica'] },
          { id: 'ctrl_materiais_contrato', label: 'Controle de materiais por contrato?', type: 'radio', opts: ['Sim','Não','Não se aplica'] },
          { id: 'ctrl_produtividade', label: 'Controle de produtividade?', type: 'radio', opts: ['Sim','Não','Não se aplica'] },
          { id: 'medicao_contratos', label: 'Medição de contratos?', type: 'radio', opts: ['Sim','Não','Não se aplica'] },
          { id: 'fat_posto', label: 'Faturamento por posto/contrato?', type: 'radio', opts: ['Sim','Não','Não se aplica'] },
          { id: 'ctrl_ponto', label: 'Controle de ponto (RH operacional)?', type: 'radio', opts: ['Sim','Não','Não se aplica'] },
          { id: 'escalas_rh', label: 'Escalas de RH?', type: 'radio', opts: ['Sim','Não','Não se aplica'] },
          { id: 'terceirizados', label: 'Terceirizados?', type: 'radio', opts: ['Sim','Não','Não se aplica'] },
          { id: 'integracao_folha', label: 'Integração com folha de pagamento?', type: 'radio', opts: ['Sim','Não','Não se aplica'] },
          { id: 'gestao_epi', label: 'Gestão de EPIs?', type: 'radio', opts: ['Sim','Não','Não se aplica'] },
        ],
      },
      // ── 10 SISTEMAS E INTEGRAÇÕES ──────────────────────────
      {
        id: 'sistemas', title: 'Sistemas & Integrações',
        desc: 'Stack tecnológico atual, integrações e avaliação do cenário',
        fields: [
          { id: 'erp_atual', label: 'ERP Atual', type: 'text', ph: 'Nome do sistema ou Nenhum' },
          { id: 'wms_atual', label: 'WMS', type: 'text', ph: 'Nome ou Nenhum' },
          { id: 'tms_atual', label: 'TMS', type: 'text', ph: 'Nome ou Nenhum' },
          { id: 'crm_sys', label: 'CRM', type: 'text', ph: 'Nome ou Nenhum' },
          { id: 'bi_atual', label: 'BI', type: 'text', ph: 'Nome ou Nenhum' },
          { id: 'rh_atual', label: 'RH / Folha', type: 'text', ph: 'Nome ou Nenhum' },
          { id: 'fiscal_sys', label: 'Fiscal', type: 'text', ph: 'Nome ou Nenhum' },
          { id: 'contabil_sys', label: 'Contábil', type: 'text', ph: 'Nome ou Nenhum' },
          { id: 'mes_sys', label: 'Produção / MES', type: 'text', ph: 'Nome ou Nenhum' },
          { id: 'manutencao_sys', label: 'Manutenção', type: 'text', ph: 'Nome ou Nenhum' },
          { id: 'bpm_sys', label: 'BPM / Workflow', type: 'text', ph: 'Nome ou Nenhum' },
          { id: 'integracoes', label: 'Integrações necessárias', type: 'chips', opts: ['Bancos','Marketplace','E-commerce','Transportadoras','Contabilidade','APIs externas','Sistemas legados','Equipamentos industriais','Coletores/WMS'] },
          { id: 'funciona', label: 'O que funciona bem hoje? (não pode perder)', type: 'textarea', ph: 'Descreva...' },
          { id: 'dificuldades', label: 'Principais dificuldades com o sistema atual', type: 'textarea', ph: 'Descreva...' },
          { id: 'planilhas', label: 'Existem planilhas paralelas ao sistema?', type: 'radio', opts: ['Sim, muitas','Algumas','Não'] },
          { id: 'nao_pode_parar', label: 'O que não pode parar na virada?', type: 'textarea', ph: 'Processos ou operações críticas...' },
          { id: 'dep_legado', label: 'Existe dependência de sistema legado?', type: 'radio', opts: ['Sim','Não'] },
        ],
      },
      // ── 11 INFRAESTRUTURA E TECNOLOGIA ─────────────────────
      {
        id: 'infra', title: 'Infraestrutura & Tecnologia',
        desc: 'Hospedagem, conectividade, suporte e equipamentos',
        fields: [
          { id: 'hospedagem', label: 'Cloud ou servidor local?', type: 'radio', opts: ['Cloud (SaaS)','Servidor local','Híbrido','A definir'] },
          { id: 'usuarios_simult', label: 'Quantidade de usuários simultâneos', type: 'number', ph: '0' },
          { id: 'filiais_conectadas', label: 'Filiais conectadas à sede?', type: 'radio', opts: ['Sim','Não','Parcialmente'] },
          { id: 'internet_tipo', label: 'Internet principal e backup', type: 'text', ph: 'Ex: Fibra 500MB + 4G backup' },
          { id: 'vpn', label: 'Existe VPN?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'ti_interno', label: 'Existe suporte de TI interno?', type: 'radio', opts: ['Sim','Não','Terceirizado'] },
          { id: 'equipamentos', label: 'Equipamentos existentes', type: 'chips', opts: ['Coletores','Impressoras térmicas','Etiquetadoras','Leitores de código','Balanças','Tablets','Equipamentos industriais integrados'] },
        ],
      },
      // ── 12 GESTÃO E INDICADORES ────────────────────────────
      {
        id: 'gestao', title: 'Gestão & Indicadores',
        desc: 'Relatórios, KPIs, maturidade de gestão e governança',
        fields: [
          { id: 'relatorios_atuais', label: 'Quais relatórios utiliza hoje? (solicitar 3 a 5 exemplos)', type: 'textarea', ph: 'Ex: 1. Relatório de estoque, 2. DRE mensal, 3. Aging de recebíveis...' },
          { id: 'freq_reunioes', label: 'Qual periodicidade de reuniões gerenciais?', type: 'text', ph: 'Ex: Semanal / Todo dia 5 do mês' },
          { id: 'kpis', label: 'KPIs acompanhados', type: 'chips', opts: ['Margem','EBITDA','CMV','OEE','SLA','Ruptura','Giro de estoque','Inadimplência','Produtividade','Rentabilidade','Forecast de vendas','Custo por produto'] },
          { id: 'proc_doc', label: 'Possui processos documentados?', type: 'radio', opts: ['Sim','Parcialmente','Não'] },
          { id: 'responsaveis_area', label: 'Responsáveis por área definidos?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'cultura_kpi', label: 'Existe cultura de indicadores?', type: 'radio', opts: ['Sim','Em desenvolvimento','Não'] },
          { id: 'governanca', label: 'Existe governança?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'pmo', label: 'Existe PMO?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'maturidade', label: 'Maturidade de Gestão (avaliação do comercial)', type: 'radio', opts: ['Alta','Média','Baixa'] },
        ],
      },
      // ── 13 PROJETO E IMPLANTAÇÃO ───────────────────────────
      {
        id: 'projeto', title: 'Projeto & Implantação',
        desc: 'Objetivos, escopo inicial, equipe do cliente e cronograma',
        fields: [
          { id: 'objetivo', label: 'Principal objetivo do projeto', type: 'textarea', ph: 'O que o cliente quer conquistar?' },
          { id: 'resultado', label: 'Resultado esperado', type: 'textarea', ph: 'KPIs ou melhorias esperadas...' },
          { id: 'dores', label: 'Principais dores atuais', type: 'textarea', ph: 'Detalhe as principais dores...' },
          { id: 'o_que_ganhar', label: 'O que deseja ganhar?', type: 'textarea', ph: 'Descreva...' },
          { id: 'nao_perder', label: 'O que não pode perder?', type: 'textarea', ph: 'Descreva...' },
          { id: 'altera_processos', label: 'Vai alterar processos internos?', type: 'radio', opts: ['Sim','Não','Parcialmente'] },
          { id: 'inicio_escopo', label: 'Por onde deseja começar?', type: 'textarea', ph: 'Módulo ou processo inicial...' },
          { id: 'implantacao_fases', label: 'Implantação por fases?', type: 'radio', opts: ['Sim','Não','A definir'] },
          { id: 'unidade_piloto', label: 'Unidade piloto?', type: 'text', ph: 'Ex: Sede SP / Filial RJ' },
          { id: 'modulos_prio', label: 'Módulos prioritários', type: 'chips', opts: ['Produção','Planejamento industrial','Estoque','Rastreabilidade','Compras','Fiscal','BI','Financeiro','RH','WMS','CRM','Facilities','Manutenção','IA'] },
          { id: 'resp_processos', label: 'Responsável por definir processos', type: 'text', ph: 'Nome e cargo' },
          { id: 'resp_cadastros', label: 'Responsável por validar cadastros', type: 'text', ph: 'Nome e cargo' },
          { id: 'resp_fiscal', label: 'Responsável por validar fiscal', type: 'text', ph: 'Nome e cargo' },
          { id: 'resp_custos', label: 'Responsável por validar custos', type: 'text', ph: 'Nome e cargo' },
          { id: 'resp_treinamentos', label: 'Responsável pelos treinamentos', type: 'text', ph: 'Nome e cargo' },
          { id: 'resp_aprovacao', label: 'Responsável por aprovar entregas / assinar documentos', type: 'text', ph: 'Nome e cargo' },
          { id: 'sponsor', label: 'Sponsor Executivo', type: 'text', ph: 'Nome e cargo' },
          { id: 'freq_status', label: 'Frequência disponível para status report', type: 'radio', opts: ['Semanal','Quinzenal','Mensal','A definir'] },
          { id: 'aprova_financeiro', label: 'Quem aprova financeiramente?', type: 'text', ph: 'Nome e cargo' },
          { id: 'go_live', label: 'Expectativa de entrada em produção', type: 'text', ph: 'Ex: Q3 2025' },
          { id: 'prazo_conclusao', label: 'Prazo esperado para conclusão do projeto', type: 'text', ph: 'Ex: 12 meses' },
          { id: 'data_critica', label: 'Existe data crítica?', type: 'radio_conditional', opts: ['Não','Sim'], conditionalOpt: 'Sim', conditionalField: { id: 'data_critica_desc', label: 'Descreva a data crítica', type: 'text', ph: 'Ex: Fechamento fiscal dezembro / Auditoria em março' } },
        ],
      },
      // ── 14 LEVANTAMENTO COMERCIAL ──────────────────────────
      {
        id: 'levantamento', title: 'Levantamento Comercial',
        desc: '⚠ O comercial deve sinalizar claramente os riscos identificados na venda',
        fields: [
          { id: 'alertas', label: 'Alertas identificados (marque todos que se aplicam)', type: 'chips', opts: ['Cliente com operação complexa','Cliente sem processos definidos','Infraestrutura ruim','Alta expectativa vs. realidade','Dependência de terceiros','Dependência de customizações','Processos muito manuais','Resistência à mudança','Alta criticidade operacional','Dependência de sistema legado','Baixa maturidade gerencial'] },
          { id: 'alertas_desc', label: 'Descrição dos alertas identificados', type: 'textarea', ph: 'Detalhe cada alerta marcado acima...' },
        ],
      },
      // ── 15 ESCOPO VENDIDO ──────────────────────────────────
      {
        id: 'escopo', title: 'Escopo Vendido',
        desc: 'O que foi efetivamente contratado e o que está fora do escopo',
        fields: [
          { id: 'modulos_vendidos', label: 'Quais módulos foram vendidos?', type: 'chips', opts: ['Produção','Planejamento industrial','Estoque','Rastreabilidade','Compras','Fiscal','BI','Financeiro','RH','WMS','CRM','Facilities','Manutenção','IA'] },
          { id: 'integracoes_contratadas', label: 'Quais integrações estão contratadas?', type: 'textarea', ph: 'Liste as integrações previstas em contrato...' },
          { id: 'customizacao', label: 'Existe customização contratada?', type: 'radio_conditional', opts: ['Não','Sim'], conditionalOpt: 'Sim', conditionalField: { id: 'customizacao_desc', label: 'Descreva a customização', type: 'textarea', ph: 'Descreva o que foi customizado...' } },
          { id: 'dev_especifico', label: 'Existe desenvolvimento específico?', type: 'radio_conditional', opts: ['Não','Sim'], conditionalOpt: 'Sim', conditionalField: { id: 'dev_especifico_desc', label: 'Descreva o desenvolvimento', type: 'textarea', ph: 'Descreva o desenvolvimento contratado...' } },
          { id: 'o_que_prometido', label: 'O que foi prometido?', type: 'textarea', ph: 'Liste compromissos assumidos na venda...' },
          { id: 'nao_existe', label: 'O que não existe atualmente no produto?', type: 'textarea', ph: 'Liste funcionalidades prometidas que ainda não existem...' },
          { id: 'nao_incluso', label: 'O que NÃO está incluso no contrato?', type: 'textarea', ph: 'Liste exclusões explícitas...' },
          { id: 'verbal', label: 'O que foi falado verbalmente (fora do contrato)?', type: 'textarea', ph: 'Compromissos verbais assumidos...' },
          { id: 'risco_comercial', label: 'Existe risco comercial?', type: 'radio_conditional', opts: ['Não','Sim'], conditionalOpt: 'Sim', conditionalField: { id: 'risco_comercial_desc', label: 'Descreva o risco comercial', type: 'textarea', ph: 'Descreva o risco...' } },
        ],
      },
      // ── 16 RISCOS E GARGALOS ───────────────────────────────
      {
        id: 'riscos', title: 'Riscos & Gargalos',
        desc: 'Mapeamento de riscos operacionais e classificação global',
        fields: [
          { id: 'gargalos', label: 'Possíveis gargalos identificados', type: 'chips', opts: ['Cadastro inconsistente','Estrutura fiscal complexa','Falta de processos definidos','Dependência de terceiros','Integrações complexas','Resistência operacional','Falta de equipe dedicada','Dados históricos inconsistentes','Infraestrutura inadequada','Multiempresa/multifilial','Alto volume operacional','Dependência de customização'] },
          { id: 'gargalos_desc', label: 'Descrição dos principais gargalos', type: 'textarea', ph: 'Detalhe os riscos identificados...' },
          { id: 'concorrencia', label: 'Concorrência em avaliação', type: 'chips', opts: ['TOTVS','Sankhya','SAP','Oracle','Datasul','Microsiga','Outro'] },
          { id: 'risco', label: 'Classificação de Risco Global', type: 'risk_tooltip' },
        ],
      },
      // ── 17 PARECER FINAL DO COMERCIAL ──────────────────────
      {
        id: 'parecer', title: 'Parecer Final do Comercial',
        desc: 'Resumo executivo e recomendações internas para a equipe de implantação',
        fields: [
          { id: 'cenario_atual', label: 'Cenário atual do cliente', type: 'textarea', ph: 'Descreva o cenário...' },
          { id: 'complexidade_op', label: 'Complexidade operacional', type: 'radio', opts: ['Baixa','Média','Alta'] },
          { id: 'complexidade_fiscal', label: 'Complexidade fiscal', type: 'radio', opts: ['Baixa','Média','Alta'] },
          { id: 'oportunidades', label: 'Oportunidades futuras identificadas', type: 'textarea', ph: 'Ex: expansão de módulos, novos contratos...' },
          { id: 'tipo_projeto', label: 'Projeto classificado como', type: 'radio', opts: ['Simples','Médio','Complexo'] },
          { id: 'necessita_gerente', label: 'Necessita Gerente de Projeto?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'necessita_consultoria', label: 'Necessita consultoria de processos?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'necessita_presencial', label: 'Necessita implantação presencial?', type: 'radio', opts: ['Sim','Não','Parcialmente'] },
          { id: 'necessita_saneamento', label: 'Necessita saneamento de cadastros?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'necessita_apoio_fiscal', label: 'Necessita apoio fiscal/contábil?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'cronograma_realista', label: 'Recomendação de cronograma realista', type: 'textarea', ph: 'Ex: Mínimo 9 meses dado a complexidade fiscal e volume de integrações...' },
          { id: 'materiais_coletar', label: 'Materiais obrigatórios a coletar antes do kick-off', type: 'chips', opts: ['Exemplos de notas fiscais','Relatórios atuais','Estrutura de produtos','Estrutura fiscal','Plano de contas','Fluxos operacionais','Organograma','Layout logístico','Estrutura de custos','Estrutura de contratos','Lista de integrações','Dados fiscais básicos'] },
          { id: 'obs', label: 'Observações finais do comercial para a equipe de implantação', type: 'textarea', ph: 'Tudo que a implantação precisa saber e não está coberto acima...' },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════
  // TECFOOD — 16 seções — espelho fiel do documento
  // ══════════════════════════════════════════════════════════
  tecfood: {
    label: 'TecFood',
    sections: [
      // ── 01 PESQUISA ────────────────────────────────────────
      {
        id: 'pesquisa', title: 'Pesquisa & Identificação',
        desc: 'Dados de identificação e fontes públicas. Clique em "Pesquisar Cliente" para enriquecer automaticamente.',
        fields: [
          { id: 'consultor_nome', label: 'Consultor Responsável', type: 'text', ph: 'Nome do consultor Teknisa' },
          { id: 'consultor_email', label: 'E-mail do Consultor Responsável', type: 'text', ph: 'consultor@teknisa.com' },
          { id: 'sponsor_nome', label: 'Sponsor Executivo — Nome', type: 'text', ph: 'Nome e cargo' },
          { id: 'sponsor_email', label: 'Sponsor Executivo — E-mail', type: 'text', ph: 'sponsor@empresa.com.br' },
          { id: 'sponsor_tel', label: 'Sponsor Executivo — Telefone', type: 'text', ph: '(11) 99999-9999' },
          { id: 'coord_nome', label: 'Coordenador do Projeto no Cliente — Nome', type: 'text', ph: 'Nome e cargo' },
          { id: 'coord_email', label: 'Coordenador do Projeto no Cliente — E-mail', type: 'text', ph: 'coordenador@empresa.com.br' },
          { id: 'coord_tel', label: 'Coordenador do Projeto no Cliente — Telefone', type: 'text', ph: '(11) 99999-9999' },
          { id: 'razao_social', label: 'Razão Social / Nome Fantasia', type: 'text', ph: 'Nome da empresa' },
          { id: 'cnpj', label: 'CNPJ Principal', type: 'text', ph: '00.000.000/0001-00' },
          { id: 'site', label: 'Site Oficial', type: 'text', ph: 'https://www.empresa.com.br' },
          { id: 'linkedin', label: 'LinkedIn (empresa)', type: 'text', ph: 'https://linkedin.com/company/...' },
          { id: 'instagram', label: 'Instagram', type: 'text', ph: 'https://instagram.com/...' },
          { id: 'research_extra', label: 'Informações descobertas na pesquisa', type: 'textarea', ph: 'Preencha automaticamente ou manualmente...' },
        ],
      },
      {
        id: 'visao', title: 'Visão Geral do Cliente',
        desc: 'Segmentos de atuação, porte e estrutura operacional',
        fields: [
          { id: 'segmento', label: 'Segmentos de Atuação', type: 'chips', opts: ['Unidade administrada','Refeições transportadas','Merenda escolar','Hospitalar','Corporativo','Industrial','Prisional','Eventos','Offshore'] },
          { id: 'tempo_op', label: 'Tempo de atuação da empresa', type: 'text', ph: 'Ex: 12 anos' },
          { id: 'regiao', label: 'Região de atuação', type: 'text', ph: 'Ex: Nacional, Sudeste...' },
          { id: 'contratos', label: 'Quantidade total de contratos ativos', type: 'number', ph: '0' },
          { id: 'matriz', label: 'Qual será a organização principal (matriz)?', type: 'text', ph: 'Ex: Sede São Paulo' },
          { id: 'unidades_op', label: 'Unidades operacionais', type: 'number', ph: '0' },
          { id: 'cozinhas', label: 'Cozinhas centrais', type: 'number', ph: '0' },
          { id: 'estoques_centrais', label: 'Estoques centrais', type: 'number', ph: '0' },
          { id: 'fabricas', label: 'Fábricas', type: 'number', ph: '0' },
          { id: 'escritorios', label: 'Escritórios / Sede', type: 'number', ph: '0' },
          { id: 'ols', label: 'OLs (Operadores Logísticos)', type: 'number', ph: '0' },
          { id: 'clientes_atendidos', label: 'Escolas / Hospitais / Clientes atendidos', type: 'number', ph: '0' },
          { id: 'fat_total', label: 'Faturamento Total (R$/ano)', type: 'text', ph: 'Ex: R$ 50 milhões' },
        ],
      },
      // ── 03 ESTRUTURA SOCIETÁRIA E FISCAL ───────────────────
      {
        id: 'fiscal', title: 'Estrutura Societária & Fiscal',
        desc: 'CNPJs, regimes tributários, obrigações fiscais e contábeis',
        fields: [
          { id: 'qtd_cnpjs', label: 'Quantidade de empresas e quais são (CNPJs)', type: 'number', ph: '0' },
          { id: 'regime', label: 'Regime tributário de cada CNPJ', type: 'regime_dynamic' },
          { id: 'insc_estaduais', label: 'Quantidade de inscrições estaduais e quais são', type: 'textarea', ph: 'Ex: 3 IEs — SP, RJ, MG' },
          { id: 'qtd_filiais_fiscal', label: 'Quantidade de filiais/unidades (fiscal)', type: 'number', ph: '0' },
          { id: 'holding', label: 'Existe Holding?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'contabilidade', label: 'Contabilidade interna ou externa?', type: 'radio', opts: ['Interna','Externa','Mista'] },
          { id: 'responsavel_fiscal', label: 'Responsável fiscal (nome e cargo)', type: 'text', ph: 'Ex: João Silva — Coordenador Fiscal' },
          { id: 'integracao_contabil', label: 'Possui integração contábil?', type: 'radio', opts: ['Sim','Não','Em implantação'] },
          { id: 'docs_fiscais', label: 'Documentos Fiscais Emitidos', type: 'chips', opts: ['NF-e modelo 55','NFC-e','CT-e','MDF-e','NFS-e'] },
          { id: 'tipos_op', label: 'Tipos de Operação Fiscal', type: 'chips', opts: ['Venda','Transferência','Industrialização','Remessa','Produção própria','Faturamento de refeições','Contratos públicos'] },
          { id: 'particularidades_fiscal', label: 'Possui particularidades fiscais por contrato?', type: 'textarea', ph: 'Descreva ou Não possui' },
          { id: 'prestacao_contas_pub', label: 'Existe obrigação de prestação de contas para clientes públicos?', type: 'radio', opts: ['Sim','Não'] },
        ],
      },
      // ── 04 ESTRUTURA OPERACIONAL ───────────────────────────
      {
        id: 'operacao', title: 'Estrutura Operacional',
        desc: 'Modelo de operação, volumes de refeições e gestão operacional',
        fields: [
          { id: 'tipo_op', label: 'Tipo de operação', type: 'chips', opts: ['Produção local','Produção centralizada','Refeição transportada','Distribuição terceirizada','Produção terceirizada'] },
          { id: 'ref_dia', label: 'Quantidade média de refeições servidas diariamente', type: 'number', ph: '0' },
          { id: 'ref_contrato', label: 'Quantidade de refeições por contrato/unidade', type: 'textarea', ph: 'Ex: Contrato A: 500 ref/dia, Contrato B: 1.200 ref/dia...' },
          { id: 'sazonalidade', label: 'Existe sazonalidade operacional?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'op_24h', label: 'Possui operação 24h?', type: 'radio', opts: ['Sim','Não','Algumas unidades'] },
          { id: 'gestao_tipo', label: 'Gestão centralizada ou descentralizada?', type: 'radio', opts: ['Centralizada','Descentralizada','Mista'] },
          { id: 'cardapio_unidade', label: 'Cada unidade monta cardápio?', type: 'radio', opts: ['Sim','Não','Parcialmente'] },
          { id: 'cardapio_central', label: 'Existe planejamento central de cardápio?', type: 'radio', opts: ['Sim','Não','Misto'] },
          { id: 'compras_tipo', label: 'Compras centralizadas?', type: 'radio', opts: ['Centralizadas','Por unidade','Mistas'] },
          { id: 'ctrl_op_contrato', label: 'Controle operacional por contrato?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'custo_contrato', label: 'Existe gestão de custo por contrato/unidade?', type: 'radio', opts: ['Sim','Não','Parcialmente'] },
          { id: 'tipo_contrato', label: 'Contratos públicos ou privados?', type: 'radio', opts: ['Públicos','Privados','Misto'] },
          { id: 'regras_contrato', label: 'Existem regras específicas por contrato?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'marca_exigida', label: 'Possui controle de marca/produto exigido pelo cliente?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'restricoes_nutricionais', label: 'Existem restrições nutricionais específicas?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'exigencias_sanitarias', label: 'Existem exigências sanitárias específicas?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'abastecimento_freq', label: 'Frequência de abastecimento por categoria', type: 'chips', opts: ['Perecíveis — diário','Secos — semanal','Congelados — quinzenal','Hortifruti — diário','Outro'] },
        ],
      },
      // ── 05 PRODUTOS, RECEITUÁRIO E PRODUÇÃO ────────────────
      {
        id: 'receituario', title: 'Produtos, Receituário & Produção',
        desc: 'Estrutura de SKUs, receituário, produção e abastecimento',
        fields: [
          { id: 'qtd_skus', label: 'Quantidade aproximada de SKUs', type: 'number', ph: '0' },
          { id: 'tipos_produto', label: 'Trabalha com', type: 'chips', opts: ['Matéria-prima','Produto acabado','Semiacabado','Produção interna','Revenda'] },
          { id: 'producao_interna', label: 'Produz/processa alimentos internamente?', type: 'radio', opts: ['Sim','Não','Parcialmente'] },
          { id: 'unidades_producao', label: 'Em quais unidades ocorre produção?', type: 'textarea', ph: 'Ex: Cozinha Central SP, Unidade ABC...' },
          { id: 'rastreab', label: 'Necessita rastreabilidade?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'ctrl_lote', label: 'Necessita controle de lote/validade? (atenção: alta complexidade)', type: 'radio', opts: ['Sim','Não','Avaliar'] },
          { id: 'rendimento', label: 'Necessita controle de rendimento?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'receituario_padrao', label: 'Possui receituário padrão?', type: 'radio', opts: ['Sim — atualizado','Sim — desatualizado','Não'] },
          { id: 'rec_especificas', label: 'Possui receitas específicas por contrato/unidade?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'receituario_atualizado', label: 'Receituário está atualizado?', type: 'radio', opts: ['Sim','Não','Parcialmente'] },
          { id: 'ctrl_nutricional', label: 'Existe controle nutricional?', type: 'radio', opts: ['Sim','Não','Em desenvolvimento'] },
          { id: 'alerg', label: 'Existe controle de alergênicos?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'tabela_nutricional', label: 'Possui tabela nutricional?', type: 'radio', opts: ['Sim','Não','Parcialmente'] },
          { id: 'transferencia_unidades', label: 'Transferência entre unidades?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'logistica_propria', label: 'Possui logística própria?', type: 'radio', opts: ['Sim','Não','Parcialmente'] },
          { id: 'roteirizacao', label: 'Existe roteirização?', type: 'radio', opts: ['Sim','Não','Em avaliação'] },
        ],
      },
      // ── 06 ESTOQUE E COMPRAS ───────────────────────────────
      {
        id: 'estoque', title: 'Estoque & Compras',
        desc: 'Inventário, perdas, compras e fornecedores',
        fields: [
          { id: 'freq_inventario', label: 'Frequência de inventário físico', type: 'select', opts: ['Selecione','Diário','Semanal','Quinzenal','Mensal','Trimestral'] },
          { id: 'inv_rotativo', label: 'Inventário rotativo ou geral?', type: 'radio', opts: ['Rotativo','Geral','Ambos'] },
          { id: 'divergencias', label: 'Possui divergências recorrentes?', type: 'radio', opts: ['Sim','Não','Às vezes'] },
          { id: 'perdas_monitoradas', label: 'Possui perdas monitoradas?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'sobra_limpa_suja', label: 'Controle de sobra limpa/suja?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'comprador_corporativo', label: 'Existe comprador corporativo?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'pedido_unidade', label: 'Cada unidade faz pedidos?', type: 'radio', opts: ['Sim','Não','Parcialmente'] },
          { id: 'fluxo_aprovacao_compras', label: 'Fluxo de aprovação de compras', type: 'textarea', ph: 'Descreva o fluxo ou Não possui' },
          { id: 'cotacao_integrada', label: 'Possui cotação integrada?', type: 'radio', opts: ['Sim','Não','Em avaliação'] },
          { id: 'contratos_fornec', label: 'Trabalha com contratos de fornecimento?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'fornec_homologados', label: 'Possui fornecedores homologados?', type: 'radio', opts: ['Sim','Não'] },
        ],
      },
      // ── 07 FINANCEIRO E FATURAMENTO ────────────────────────
      {
        id: 'financeiro', title: 'Financeiro & Faturamento',
        desc: 'Estrutura financeira, faturamento e controle por contrato',
        fields: [
          { id: 'fat_total_fin', label: 'Faturamento total da empresa (R$/ano)', type: 'text', ph: 'Ex: R$ 50 milhões' },
          { id: 'fat_contrato', label: 'Faturamento por contrato/unidade?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'periodicidade', label: 'Periodicidade de Faturamento', type: 'chips', opts: ['Diário','Decendial','Quinzenal','Mensal'] },
          { id: 'ctrl_cc', label: 'Controle por centro de custo?', type: 'radio', opts: ['Sim','Não','Em implantação'] },
          { id: 'ctrl_contrato_fin', label: 'Controle por contrato?', type: 'radio', opts: ['Sim','Não','Em implantação'] },
          { id: 'custo_ref', label: 'Acompanha custo por refeição?', type: 'radio', opts: ['Sim','Não','Manual'] },
          { id: 'bancos', label: 'Quais bancos utiliza?', type: 'text', ph: 'Ex: Itaú, Bradesco, Banco do Brasil...' },
          { id: 'cnab', label: 'Utiliza CNAB?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'conciliacao_bancaria', label: 'Possui conciliação bancária?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'cnab_implantacao', label: 'CNAB será implantado?', type: 'radio', opts: ['Sim','Não','A definir'] },
          { id: 'plano_contas', label: 'Já existe Plano de Contas padrão a ser importado?', type: 'radio', opts: ['Sim, já disponível','Não, será criado','A definir'] },
        ],
      },
      // ── 08 PONTO DE VENDA E OPERAÇÃO COMERCIAL ─────────────
      {
        id: 'pdv', title: 'Ponto de Venda & Operação Comercial',
        desc: 'PDV, formas de pagamento, adquirência e TEF',
        fields: [
          { id: 'possui_pdv', label: 'Possui ponto de venda em alguma unidade?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'modelo_pdv', label: 'Modelo de PDV utilizado', type: 'chips', opts: ['PDV tradicional','SmartPOS','Honest Market','Autoatendimento','Totem'] },
          { id: 'qtd_caixas', label: 'Quantidade de caixas', type: 'number', ph: '0' },
          { id: 'formas_pagamento', label: 'Formas de pagamento aceitas', type: 'chips', opts: ['Dinheiro','Crédito','Débito','PIX','Vale Refeição','Vale Alimentação','Crédito próprio','Cortesia','Ticket'] },
          { id: 'adquirentes', label: 'Adquirentes utilizadas', type: 'chips', opts: ['Rede','Cielo','Stone','GetNet','Safra','PagSeguro','Outro'] },
          { id: 'tef', label: 'Utiliza TEF?', type: 'radio', opts: ['Sim','Não','Em avaliação'] },
          { id: 'modelo_smartpos', label: 'Modelo de SmartPOS (se aplicável)', type: 'text', ph: 'Ex: Sunmi D3 Pro, PAX A920...' },
          { id: 'conciliador', label: 'Possui conciliador financeiro?', type: 'radio', opts: ['Sim','Não','Em avaliação'] },
          { id: 'adquirencia_contratada', label: 'Já possui adquirência contratada?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'bandeiras', label: 'Bandeiras aceitas', type: 'chips', opts: ['Visa','Mastercard','Elo','American Express','Hipercard','Alelo','Ticket','VR','Sodexo'] },
        ],
      },
      // ── 09 SISTEMAS E INTEGRAÇÕES ──────────────────────────
      {
        id: 'sistemas', title: 'Sistemas & Integrações',
        desc: 'Stack tecnológico atual, integrações e avaliação do cenário',
        fields: [
          { id: 'erp_atual', label: 'ERP Atual', type: 'text', ph: 'Nome do sistema ou Nenhum' },
          { id: 'sys_operacional', label: 'Sistema Operacional (gestão de UAN)', type: 'text', ph: 'Nome ou Nenhum' },
          { id: 'sys_nutricional', label: 'Sistema Nutricional', type: 'text', ph: 'Nome ou Nenhum' },
          { id: 'sys_financeiro', label: 'Sistema Financeiro', type: 'text', ph: 'Nome ou Nenhum' },
          { id: 'sys_fiscal', label: 'Sistema Fiscal', type: 'text', ph: 'Nome ou Nenhum' },
          { id: 'bi_atual', label: 'BI / Relatórios', type: 'text', ph: 'Nome ou Nenhum' },
          { id: 'rh_atual', label: 'RH / Folha', type: 'text', ph: 'Nome ou Nenhum' },
          { id: 'sys_estoque', label: 'Controle de Estoque', type: 'text', ph: 'Nome ou Nenhum' },
          { id: 'sys_producao', label: 'Controle de Produção', type: 'text', ph: 'Nome ou Nenhum' },
          { id: 'integracoes', label: 'Integrações necessárias', type: 'chips_conditional', opts: ['Contabilidade','Sistemas do cliente contratante','Portal de compras','BI','RH','Apps operacionais','APIs externas','Operador logístico (OL)','Outros'], conditionalOpt: 'Outros', conditionalField: { id: 'integracoes_outros', label: 'Quais outras integrações?', type: 'text', ph: 'Descreva as outras integrações...' } },
          { id: 'funciona', label: 'O que funciona bem hoje? (não pode perder)', type: 'textarea', ph: 'Descreva...' },
          { id: 'dificuldades', label: 'Principais dificuldades atuais', type: 'textarea', ph: 'Descreva...' },
          { id: 'nao_pode_parar', label: 'O que não pode parar na virada?', type: 'textarea', ph: 'Processos ou operações críticas...' },
        ],
      },
      // ── 10 INFRAESTRUTURA E HARDWARE ───────────────────────
      {
        id: 'infra', title: 'Infraestrutura & Hardware',
        desc: 'Estrutura das unidades, conectividade e equipamentos',
        fields: [
          { id: 'estrutura_unidades', label: 'Estrutura das unidades', type: 'chips', opts: ['Computadores','Tablets','Celulares','Servidores','SmartPOS'] },
          { id: 'internet_tipo', label: 'Internet principal e backup', type: 'text', ph: 'Ex: Fibra 100MB + 4G backup' },
          { id: 'rede_tipo', label: 'Rede cabeada ou Wi-Fi?', type: 'radio', opts: ['Cabeada','Wi-Fi','Mista'] },
          { id: 'ti_interno', label: 'Existe suporte de TI interno?', type: 'radio', opts: ['Sim','Não','Terceirizado'] },
          { id: 'equipamentos', label: 'Equipamentos existentes', type: 'chips', opts: ['Impressoras','Impressoras térmicas','Etiquetadoras','Balanças','Coletores','Leitores','Equipamentos de produção integrados'] },
        ],
      },
      // ── 11 GESTÃO E INDICADORES ────────────────────────────
      {
        id: 'gestao', title: 'Gestão & Indicadores',
        desc: 'Relatórios, KPIs, maturidade de gestão e tomada de decisão',
        fields: [
          { id: 'relatorios_atuais', label: 'Quais relatórios utiliza hoje? (solicitar 3 a 5 exemplos)', type: 'textarea', ph: 'Ex: 1. Custo por refeição, 2. CMV mensal, 3. Relatório de cardápio...' },
          { id: 'relatorios_upload', label: 'Anexar relatórios (imagens ou PDFs)', type: 'drive_upload', ph: 'Enviar arquivos para o Google Drive' },
          { id: 'reuniao_gestao', label: 'Qual dia do mês ocorre reunião gerencial?', type: 'text', ph: 'Ex: Todo dia 5 / Segunda semana do mês' },
          { id: 'kpis', label: 'Indicadores acompanhados', type: 'chips', opts: ['CMV','Custo por refeição','Desperdício','Produtividade','Ruptura','SLA','Resultado por contrato','Consumo per capita'] },
          { id: 'nivel_organizacao', label: 'Nível de organização do cliente', type: 'radio', opts: ['Alto','Médio','Baixo'] },
          { id: 'proc_doc', label: 'Possui processos documentados?', type: 'radio', opts: ['Sim','Parcialmente','Não'] },
          { id: 'cultura_kpi', label: 'Existe cultura de indicadores?', type: 'radio', opts: ['Sim','Em desenvolvimento','Não'] },
          { id: 'responsaveis_area', label: 'Responsáveis por área definidos?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'decisao_operacional', label: 'Quem toma decisão operacional?', type: 'text', ph: 'Nome e cargo' },
          { id: 'aprova_mudancas', label: 'Quem aprova mudanças?', type: 'text', ph: 'Nome e cargo' },
          { id: 'maturidade', label: 'Maturidade de Gestão (avaliação do comercial)', type: 'radio', opts: ['Alta','Média','Baixa'] },
          { id: 'planilhas', label: 'Existem controles paralelos em planilhas?', type: 'radio_conditional', opts: ['Não','Sim'], conditionalOpt: 'Sim', conditionalField: { id: 'planilhas_upload', label: 'Enviar planilhas para o Google Drive', type: 'drive_upload' } },
        ],
      },
      // ── 12 PROJETO E IMPLANTAÇÃO ───────────────────────────
      {
        id: 'projeto', title: 'Projeto & Implantação',
        desc: 'Objetivos, escopo inicial, equipe do cliente e cronograma',
        fields: [
          { id: 'objetivo', label: 'Principal objetivo do projeto', type: 'textarea', ph: 'O que o cliente quer conquistar?' },
          { id: 'resultado', label: 'Resultado esperado', type: 'textarea', ph: 'KPIs ou melhorias esperadas...' },
          { id: 'dores', label: 'Principais dores atuais', type: 'textarea', ph: 'Detalhe as principais dores...' },
          { id: 'altera_processos', label: 'Vai alterar processos atuais?', type: 'radio', opts: ['Sim','Não','Parcialmente'] },
          { id: 'o_que_ganhar', label: 'O que deseja ganhar?', type: 'textarea', ph: 'Descreva...' },
          { id: 'nao_perder', label: 'O que não pode perder?', type: 'textarea', ph: 'Descreva...' },
          { id: 'inicio_escopo', label: 'Por onde deseja começar?', type: 'textarea', ph: 'Módulo ou processo inicial...' },
          { id: 'unidade_piloto', label: 'Unidade piloto?', type: 'text', ph: 'Ex: Unidade ABC / Cozinha Central SP' },
          { id: 'contrato_piloto', label: 'Contrato piloto?', type: 'text', ph: 'Ex: Contrato XYZ — 500 ref/dia' },
          { id: 'modulos_prio', label: 'Módulos Contratados Prioritários (marque até 3)', type: 'chips', opts: ['Receituário','Produção','Estoque','Compras','Financeiro','Fiscal','PDV','BI','Nutrição','Contratos','IA','Abastecimento'] },
          { id: 'resp_processos', label: 'Responsável por definir processos', type: 'text', ph: 'Nome e cargo' },
          { id: 'resp_arvore_produtos', label: 'Responsável por definir árvore de produtos', type: 'text', ph: 'Nome e cargo' },
          { id: 'resp_receituario', label: 'Responsável por validar receituário', type: 'text', ph: 'Nome e cargo' },
          { id: 'resp_contratos', label: 'Responsável por validar contratos', type: 'text', ph: 'Nome e cargo' },
          { id: 'resp_cadastros', label: 'Responsável por realizar cadastros', type: 'text', ph: 'Nome e cargo' },
          { id: 'resp_treinamentos', label: 'Responsável por participar de treinamentos', type: 'text', ph: 'Nome e cargo' },
          { id: 'resp_aprovacao', label: 'Responsável por aprovar entregas / assinar documentos', type: 'text', ph: 'Nome e cargo' },
          { id: 'freq_status', label: 'Frequência disponível para status report', type: 'radio', opts: ['Semanal','Quinzenal','Mensal','A definir'] },
          { id: 'aprova_financeiro', label: 'Quem aprova financeiramente?', type: 'text', ph: 'Nome e cargo' },
          { id: 'go_live', label: 'Expectativa de entrada em produção', type: 'text', ph: 'Ex: Q4 2025' },
          { id: 'prazo_conclusao', label: 'Prazo esperado para conclusão do projeto', type: 'text', ph: 'Ex: 8 meses' },
          { id: 'custos_visitas', label: 'Foi mencionado sobre custos de agendas/visitas presenciais?', type: 'radio', opts: ['Sim, cliente ciente','Não se aplica'] },
          { id: 'concorrencia', label: 'Concorrência em avaliação', type: 'chips_conditional', opts: ['Genial','NL','Totvs','Sankhya','Nutriplus','Eprocorpo','Oracle Food','SAP','Outro'], conditionalOpt: 'Outro', conditionalField: { id: 'concorrencia_outro', label: 'Qual outro concorrente?', type: 'text', ph: 'Nome do concorrente...' } },
          { id: 'data_critica', label: 'Existe data crítica?', type: 'radio_conditional', opts: ['Não','Sim'], conditionalOpt: 'Sim', conditionalField: { id: 'data_critica_desc', label: 'Descreva a data crítica', type: 'text', ph: 'Ex: Renovação contratual em março / Início de licitação em fev/26' } },
        ],
      },
      // ── 13 LEVANTAMENTO COMERCIAL ──────────────────────────
      {
        id: 'levantamento', title: 'Levantamento Comercial',
        desc: '⚠ O comercial deve sinalizar claramente os riscos identificados na venda',
        fields: [
          { id: 'alertas', label: 'Alertas identificados (marque todos que se aplicam)', type: 'chips', opts: ['Cliente com operação complexa','Cliente sem processos definidos','Infraestrutura ruim','Alta expectativa vs. realidade','Dependência de terceiros','Dependência do cliente contratante','Operação altamente personalizada','Equipe resistente à mudança','Falta de padronização operacional','Baixa maturidade gerencial'] },
          { id: 'alertas_desc', label: 'Descrição dos alertas identificados', type: 'textarea', ph: 'Detalhe cada alerta marcado acima...' },
        ],
      },
      // ── 14 ESCOPO VENDIDO ──────────────────────────────────
      {
        id: 'escopo', title: 'Escopo Vendido',
        desc: 'O que foi efetivamente contratado e o que está fora do escopo',
        fields: [
          { id: 'modulos_vendidos', label: 'Quais módulos foram vendidos?', type: 'chips', opts: ['Receituário','Produção','Estoque','Compras','Financeiro','Fiscal','PDV','BI','Nutrição','Contratos','IA','Abastecimento'] },
          { id: 'integracoes_contratadas', label: 'Quais integrações estão contratadas?', type: 'textarea', ph: 'Liste as integrações previstas em contrato...' },
          { id: 'customizacao', label: 'Existe customização contratada?', type: 'radio_conditional', opts: ['Não','Sim'], conditionalOpt: 'Sim', conditionalField: { id: 'customizacao_desc', label: 'Descreva a customização', type: 'textarea', ph: 'Descreva o que foi customizado...' } },
          { id: 'o_que_prometido', label: 'O que foi prometido?', type: 'textarea', ph: 'Liste compromissos assumidos na venda...' },
          { id: 'nao_existe', label: 'O que ainda não existe no produto?', type: 'textarea', ph: 'Liste funcionalidades prometidas que ainda não existem...' },
          { id: 'nao_incluso', label: 'O que NÃO está incluso no contrato?', type: 'textarea', ph: 'Liste exclusões explícitas...' },
          { id: 'verbal', label: 'O que foi falado verbalmente (fora do contrato)?', type: 'textarea', ph: 'Compromissos verbais assumidos...' },
          { id: 'risco_comercial', label: 'Existe risco comercial?', type: 'radio_conditional', opts: ['Não','Sim'], conditionalOpt: 'Sim', conditionalField: { id: 'risco_comercial_desc', label: 'Descreva o risco comercial', type: 'textarea', ph: 'Descreva o risco...' } },
        ],
      },
      // ── 15 RISCOS E GARGALOS ───────────────────────────────
      {
        id: 'riscos', title: 'Riscos & Gargalos',
        desc: 'Mapeamento de riscos operacionais e classificação global',
        fields: [
          { id: 'gargalos', label: 'Possíveis gargalos identificados', type: 'chips', opts: ['Receituário inconsistente','Falta de padronização','Dependência do cliente contratante','Processos manuais','Falta de inventário inicial','Internet instável','Complexidade contratual','Complexidade fiscal','Multiempresa/multicontrato','Resistência operacional','Falta de equipe dedicada do cliente','Dependência de terceiros'] },
          { id: 'gargalos_desc', label: 'Descrição dos principais gargalos', type: 'textarea', ph: 'Detalhe os riscos identificados...' },
          { id: 'concorrencia', label: 'Concorrência em avaliação', type: 'chips', opts: ['Nutriplus','Eprocorpo','Oracle Food','SAP','Totvs','Outro'] },
          { id: 'risco', label: 'Classificação de Risco Global', type: 'risk_tooltip' },
        ],
      },
      // ── 16 PARECER FINAL DO COMERCIAL ──────────────────────
      {
        id: 'parecer', title: 'Parecer Final do Comercial',
        desc: 'Resumo executivo e recomendações internas para a equipe de implantação',
        fields: [
          { id: 'cenario_atual', label: 'Cenário atual do cliente', type: 'textarea', ph: 'Descreva o cenário...' },
          { id: 'complexidade_op', label: 'Complexidade operacional', type: 'radio', opts: ['Baixa','Média','Alta'] },
          { id: 'complexidade_contratual', label: 'Complexidade contratual', type: 'radio', opts: ['Baixa','Média','Alta'] },
          { id: 'expectativa_cliente', label: 'Expectativa do cliente', type: 'radio', opts: ['Alinhada com o produto','Parcialmente alinhada','Acima do produto'] },
          { id: 'oportunidades', label: 'Oportunidades futuras identificadas', type: 'textarea', ph: 'Ex: expansão de módulos, novos contratos, cross-sell...' },
          { id: 'tipo_projeto', label: 'Projeto classificado como', type: 'radio', opts: ['Simples','Médio','Complexo'] },
          { id: 'necessita_gerente', label: 'Necessita Gerente de Projeto?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'necessita_consultoria', label: 'Necessita consultoria operacional?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'necessita_presencial', label: 'Necessita implantação presencial?', type: 'radio', opts: ['Sim','Não','Parcialmente'] },
          { id: 'necessita_treinamento', label: 'Necessita treinamento avançado?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'necessita_saneamento', label: 'Necessita saneamento de cadastros?', type: 'radio', opts: ['Sim','Não'] },
          { id: 'cronograma_realista', label: 'Recomendação de cronograma realista', type: 'textarea', ph: 'Ex: Mínimo 6 meses dado a complexidade do receituário e volume de contratos...' },
          { id: 'materiais_coletar', label: 'Materiais obrigatórios a coletar antes do kick-off', type: 'chips', opts: ['Exemplos de notas fiscais','Relatórios atuais','Estrutura de contratos','Cardápios','Receituários','Estrutura de SKUs','Layout operacional','Fluxo de abastecimento','Lista de unidades','Contratos de fornecimento','Estrutura de centros de custo','Exemplos de faturamento','Dados fiscais básicos'] },
          { id: 'obs', label: 'Observações finais do comercial para a equipe de implantação', type: 'textarea', ph: 'Tudo que a implantação precisa saber e não está coberto acima...' },
        ],
      },
    ],
  },
}
